# Generated by Django 4.2.7 on 2026-04-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['date'], name='analytics_a_date_67feca_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['severity'], name='analytics_a_severit_30fa75_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['region'], name='analytics_a_region_bdcc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['date'], name='analytics_p_date_1c75d1_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model_version'], name='analytics_p_model_v_e10e56_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['date'], name='analytics_s_date_38deac_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['region'], name='analytics_s_region_1b51df_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['product_id'], name='analytics_s_product_421b6f_idx'),
        ),
    ]
