# Generated by Django 4.2.7 on 2026-07-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organisation_plan_user_last_usage_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_token',
            field=models.TextField(unique=True),
        ),
    ]
